### ISSUE TITLE
蓝牙不正常

### ISSUE THREAD

**Issue by weidongbcn** [zxystd/itlwm#105]
我用9560ac 已经可以连接到网络了，但是蓝牙不工作，扫描不到附近的设备，也不能被附近的设备认识。

**Comment by zxystd** [comment]
![image](https://user-images.githubusercontent.com/16227538/83933193-0a411280-a7d9-11ea-90e8-3b86840e79cb.png)
![Screenshot_2020-06-06-09-36-09-661_com miui home](https://user-images.githubusercontent.com/16227538/83933209-3492d000-a7d9-11ea-9822-9a69a4c48cf6.jpg)

经测试蓝牙可以工作哦.
