### ISSUE TITLE
Intel Dual Band AC3165 - Test

### ISSUE THREAD

**Issue by arch-dev** [zxystd/itlwm#106]
Hi, after using latest commits no more kernel panic. So thank you again @zxystd. I have opened this issue to post SpeedTest and other related test for AC3165 chipset.
Here there are the best SpeedTest results for it. If I can test something else please tell me @zxystd.
[speedtests-2020-06-01-193643.csv.zip](https://github.com/zxystd/itlwm/files/4713223/speedtests-2020-06-01-193643.csv.zip)

**Comment by m0d16l14n1** [comment]
@arch-dev Hello, do you use WEP or WPA2? Can you share compiled kext please? I had 3165 too, but i use some old compiled kext and it`s didn`t work with WPA2

**Comment by arch-dev** [comment]
I have a mixed security protocol (WPA/WPA2) so I don't know which of those I'm using now but soon I will update prebuilt kext so you can try.

**Comment by m0d16l14n1** [comment]
@arch-dev okay, waiting. big thx!

**Comment by leopck** [comment]
I'm using AC3165 as well. Here's my speedtest for some comparison. MY actual internet speed is 300Mbps.

![](https://www.speedtest.net/result/9536642100.png)

Running AC3165 on WPA/WPA2 is no issue. Besides the audio via Intel Bluetooth being affected so far, it's just the speed performance on this could be better.

**Comment by arch-dev** [comment]
@m0d16l14n1 try this kext
[itlwm.kext.zip](https://github.com/zxystd/itlwm/files/4716523/itlwm.kext.zip)

**Comment by m0d16l14n1** [comment]
@arch-dev works great, thx for sharing it with me! Got 32 Mbps download and 11.73 Mbps upload using WPA/WPA2. That's great. Btw, WiFi 5 is supported or not?

**Comment by williambj1** [comment]
no, only Wi-Fi 4, 802.11n

**Comment by m0d16l14n1** [comment]
@williambj1 okay. Even with WiFi it`s cool. I can stop use tethering. That`s great work! Big thx @zxystd!
