### ISSUE TITLE
Work on Clover BUT NOT WORK on Opencore

### ISSUE THREAD

**Issue by dwd11511** [zxystd/itlwm#109]
clover版本5118，oc用的远景的mod版；
在clover下wifi可用，到了oc就不行。
itlwm.kext用的是同一个文件。网卡是9560ac。
附上clover和oc的kext文件夹截图及oc下itlwm的日志
<img width="425" alt="截屏2020-06-05 下午3 25 18" src="https://user-images.githubusercontent.com/37724877/83849076-72dcb080-a741-11ea-8ca0-d64343567138.png">
<img width="322" alt="截屏2020-06-05 下午3 27 44" src="https://user-images.githubusercontent.com/37724877/83848927-2e511500-a741-11ea-83a1-ed8c436bd49e.png">
[test.log](https://github.com/zxystd/itlwm/files/4734515/test.log)

**Comment by zxystd** [comment]
oc可以确认是可以成功加载使用的。看log是没有找到网卡，你的oc efi有问题，检查是否屏蔽了网卡。

**Comment by dwd11511** [comment]
已解决，是efi的问题而非itlwm问题。
