### ISSUE TITLE
ac9560

### ISSUE THREAD

**Issue by yiseni** [zxystd/itlwm#11]
你好，我想问一下，在远景论坛我看到已经支持9系的wifi,但为什么在源码中并没有9系的驱动？

**Comment by williambj1** [comment]
https://github.com/zxystd/itlwm/tree/feature-openbsd-newest

**Comment by yiseni** [comment]
谢谢

**Comment by quan3c10** [comment]
> 谢谢

Have you try the newest? Does it work with 9560?

**Comment by yiseni** [comment]
ac9560 is recognized and driven normally in the pci directory, but it cannot be connected to the network, and the startup and shutdown speed is slow, and you need to wait.

**Comment by quan3c10** [comment]
Sure, I am using the IntelBluetooth kext from @zxystd and believe he will make the Wifi works soon.

**Comment by mn19941219** [comment]
> ac9560 is recognized and driven normally in the pci directory, but it cannot be connected to the network, and the startup and shutdown speed is slow, and you need to wait.

Try to install kext to L/E not clover/Kext/Other

**Comment by yiseni** [comment]
I will try,thanks.

**Comment by MarshalX** [comment]
> > ac9560 is recognized and driven normally in the pci directory, but it cannot be connected to the network, and the startup and shutdown speed is slow, and you need to wait.
> 
> Try to install kext to L/E not clover/Kext/Other

I think it`s very bad idea) Use kextload only

**Comment by quan3c10** [comment]
> I will try,thanks.

Does this work? As you closed this issue.

**Comment by williambj1** [comment]
It works for me, 9560ac 8086;A370.

You do need some skills to load the kext properly.
Not quite stable, don't expect too much.

**Comment by quan3c10** [comment]
> It works for me, 9560ac 8086;A370.
> 
> You do need some skills to load the kext properly.
> Not quite stable, don't expect too much.

It better to hear that. So it is just the time to make it fully works, I will wait till the stable version is released.
