### ISSUE TITLE
The Internet connect stops after time

### ISSUE THREAD

**Issue by xrokz** [zxystd/itlwm#110]
It working very well but after some hours the connection ends and the eathernet says `Not Connected`

**Comment by arch-dev** [comment]
Yes for me too but after lot of time about 6 hours of use.

**Comment by zxystd** [comment]
Can you try the latest commit? I am not sure I have solve this. Because I haven't met that and nobody send me the log when it disconnect.

**Comment by xrokz** [comment]
where i can find the log ?

**Comment by zxystd** [comment]
I think I have fix the disconnect issue, you can try the latest commit.

**Comment by arch-dev** [comment]
So I've checked... No more disconnection issues. Will check again when I go back home

**Comment by xrokz** [comment]
thanks but the version i use is compiled by a friend so i want to know how to compile ..
