### ISSUE TITLE
Intel® Centrino® Ultimate-N 6300 support

### ISSUE THREAD

**Issue by Alexander-69** [zxystd/itlwm#112]
Can you get  Intel® Centrino® Ultimate-N 6300to work?
[https://ark.intel.com/content/www/us/en/ark/products/59474/intel-centrino-ultimate-n-6300-dual-band.html](https://ark.intel.com/content/www/us/en/ark/products/59474/intel-centrino-ultimate-n-6300-dual-band.html)

**Comment by zxystd** [comment]
These cards are out of date, we have more better choices. So they will not be supported. Thanks.

**Comment by giovannidirenzo** [comment]
That’s sad

**Comment by zxystd** [comment]
OpenBSD has `iwn` driver support this card, and I can port it in itlwm, but I don't have too much time doing this(need to debug and post maintenance), there is still leave too much thing need to do in new cards support. So Sorry to say this.

**Comment by zxystd** [comment]
@Alexander-69 @tardar now you can use the latest 1.2.0-alpha version to test.

**Comment by althiometer** [comment]
i have a 6205 Thinkpad Carbon, do i need to compile itlwm to test it?

**Comment by althiometer** [comment]
nvm, got it, gonna test now
