### ISSUE TITLE
待机一晚后断网

### ISSUE THREAD

**Issue by lilmik** [zxystd/itlwm#113]
待机一晚后断网,直接重启电脑无法自动联网.
删除网络设置里面的wifi以太网连接后重启,可恢复联网.
网卡是:Killer Wireless-AC 1550i

**Comment by zxystd** [comment]
下次断网的时候麻烦收集下日志发给我,不然我没办法确认是什么问题.

log show --last 30m | grep itlwm >itlwm_log.txt

这是收集30分钟内的日志.谢谢.

**Comment by lilmik** [comment]
接连测试了几天，问题一直不再重现。。。。。

**Comment by zxystd** [comment]
用最新版的吧，已经不会再掉线
