### ISSUE TITLE
热启动后断网|网速明显慢于windows下网速

### ISSUE THREAD

**Issue by lilmik** [zxystd/itlwm#116]
用的是最新的6.7日的驱动，热启动之后断网。
同样测试环境下，黑苹果的intel无线网卡网速约为win10下的四分之一。
日志如下。
[itlwm_log.txt](https://github.com/zxystd/itlwm/files/4744480/itlwm_log.txt)

**Comment by zxystd** [comment]
网卡型号？网卡Product ID？
网速慢是指的多少mbps

**Comment by lilmik** [comment]
> 网卡型号？网卡Product ID？
> 网速慢是指的多少mbps
网卡型号：Killer Wireless-AC 1550i，网卡Product ID应该是9560吧？
网速在win10下用5g wifi 测试上传下载都能有250Mbps，在黑苹果下只有50Mbps左右 
![064039epexapxamzsuzmbq](https://user-images.githubusercontent.com/24759191/84010870-382c7f80-a9b0-11ea-809e-f7f5c71b2e19.png)

**Comment by lilmik** [comment]
mac下网络测试：
wifi状态：
<img width="783" alt="截屏2020-06-08 17 52 38" src="https://user-images.githubusercontent.com/24759191/84011333-eb957400-a9b0-11ea-9a5d-6cd5e86df464.png">
有线状态：
<img width="819" alt="截屏2020-06-08 17 54 17" src="https://user-images.githubusercontent.com/24759191/84011445-17185e80-a9b1-11ea-855c-a496bf9ce579.png">

**Comment by lilmik** [comment]
Win10 下测速
wifi状态:
![image](https://user-images.githubusercontent.com/24759191/84011929-c2c1ae80-a9b1-11ea-9774-0e4a9e700c73.png)
有线状态:
![image](https://user-images.githubusercontent.com/24759191/84011994-d66d1500-a9b1-11ea-8324-f089eef29bdb.png)

**Comment by zxystd** [comment]
正常，因为现在只有11n 20mhz的速度，而且没有tx聚合，自然速度慢，慢速是60~80mbps左右吧，这不属于bug。

**Comment by lilmik** [comment]
原来是这个原因，谢谢~
已经能使用上就相当不错了~
我有试了下Linux Deepin的速度，可能也是因为驱动的原因，速度还要更慢~
![截图录屏_选择区域_20200608180818](https://user-images.githubusercontent.com/24759191/84012914-3adca400-a9b3-11ea-97d0-d8611036bf3f.png)

**Comment by zxystd** [comment]
嗯，等后续开发支持更多802.11特性吧，这样速度就会上去了。

**Comment by lilmik** [comment]
感谢~
话说，6.7版本的驱动比6.3版本的驱动热启动掉网卡好像更严重。。。。

**Comment by zxystd** [comment]
热启动的问题我需要人跟我一起调试，具体是驱动固件版本不一致还是pcie的状态未重置导致的问题我不确定，我自己的3165,8260,9260全都没有这个问题，根本没办法测试，好像只有9560才有这个问题。
