### ISSUE TITLE
关于隐藏WIFI无法连接

### ISSUE THREAD

**Issue by Code-God1024** [zxystd/itlwm#118]
隐藏的WIFI无法连接，取消隐藏就可以连接了，请问目前不支持连接隐藏WIFI吗

**Comment by JunkuiZhang** [comment]
我也是这样...隐藏了wifi且添加了白名单，无法连接

**Comment by zxystd** [comment]
https://github.com/zxystd/itlwm/issues/100#issue-627906680

重复的问题，可以在链接中讨论，我这里先关闭这个问题。
另外现在确实不支持隐藏WiFi的连接，后续会添加支持。谢谢。
