### ISSUE TITLE
希望增加更多intel Wi-Fi的支持，我的是intel 6205。并且增加clover的支持，方法越简单越好。顶礼膜拜中～

### ISSUE THREAD

**Issue by YHSM** [zxystd/itlwm#12]

**Comment by zxystd** [comment]
Thanks for your support, bug intel6205 is not MVM constructor wireless card, this structor is now out of date, so I will not support these, you can choose the newest like AC9560, AX200 etc.

**Comment by Schaka** [comment]
Is there any way by spoofing it to appear as a similar card? I just acquired old hardware and a different card isn't really within my budget atm.
