### ISSUE TITLE
Upload Kext

### ISSUE THREAD

**Issue by tolgasonkaya** [zxystd/itlwm#120]
Hello there. Sometimes I can't compile kext with XCode. Upload latest kext in Google Drive please.

**Comment by H15teve** [comment]
You can download the compiled kext in Chinese forum PCBeta. Visit it from README

**Comment by Yomanz** [comment]
> You can download the compiled kext in Chinese forum PCBeta. Visit it from README

The forums require an invitation code apparently.

**Comment by williambj1** [comment]
Learn Xcode or wait, it's up to you.

**Comment by Yomanz** [comment]
I ran `xcodebuild` but it didn't give me a kext.

**Comment by levisliujunqi** [comment]
[itlwm0607.kext.zip](https://github.com/zxystd/itlwm/files/4752120/itlwm0607.kext.zip)
I downloaded it for you from PCBeta

**Comment by Yomanz** [comment]
> [itlwm0607.kext.zip](https://github.com/zxystd/itlwm/files/4752120/itlwm0607.kext.zip)
> I downloaded it for you from PCBeta

Thank you very much

**Comment by johnnync13** [comment]
running xcode to me the kext not appear in folder. if i use fw_gen.sh it appears this:
./fw_gen.sh: line 20: /itlwm/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 21: /itlwm/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 35: /itlwm/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 37: /itlwm/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 46: /itlwm/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 47: /itlwm/FwBinary.cpp: No such file or directory
