### ISSUE TITLE
huawei

### ISSUE THREAD

**Issue by fejxc** [zxystd/itlwm#123]
9650 从win10到Mac 还是不能用wifi，需要关机，再次重启可以用

**Comment by wklxd** [comment]
已知问题，作者已经回答过好几遍了，win会把网卡放在一个错误的状态，就是要关机放电

**Comment by zxystd** [comment]
https://github.com/zxystd/itlwm/issues/131#issue-638100205

duplicate issue, I will close it. you can discuss in link issue. thank you.
