### ISSUE TITLE
No Wifi In Settings Even After Loading the Kext.

### ISSUE THREAD

**Issue by KratosAurion400** [zxystd/itlwm#126]
So When I load the Kext then try to look for wifi there's nothing. And even after restarting and reloading the next I still don't see wifi. I have an OKN Wifi 6 AX200 PCI Card if that helps.

**Comment by zxystd** [comment]
https://github.com/zxystd/itlwm/issues/36#issue-600504328

duplicate issue. btw, ax200 is worked now.
