### ISSUE TITLE
Latest version as of June 12 compiles to ¼ of the previous kext

### ISSUE THREAD

**Issue by alikaylan** [zxystd/itlwm#128]
June 12 version compiles successfully including firmware, size is ¼ of what it was compared to the previous day's code (4k vs. 16k) (clean build), does not work at all on 7265 whereas the previous day's code worked just fine. Says wire unplugged in the System Preferences. Taking this opportunity, many thanks to you for taking it this far where we have almost a fully functional Intel WiFi. Cheers.

**Comment by zxystd** [comment]
oh, that's due to my mistake of project configuration, thank you for figuring out this, will soon fix it.
