### ISSUE TITLE
how can I install it?

### ISSUE THREAD

**Issue by abdullah-abunada** [zxystd/itlwm#13]
Hello,

thank you for the amazing effort, but can you clarify how can we install it, please?

Best,

**Comment by vladdenisov** [comment]
Hello! 
You can try instructions [here](https://github.com/johnnync13/Xiaomi-Mi-Air/blob/master/WIFI/README.md).
If you have AC 8260 download kext from [here](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/issues/330#issuecomment-600749608).

**Comment by williambj1** [comment]
The kext is currently at a very early stage, extremely unstable and can't be considered usable, so the developer doesn't expect anyone who doesn't have debugging skills to mess up with their systems. Of course, you have the right to give it a try.

**Comment by abdullah-abunada** [comment]
Hi,
I have this card, Intel Wireless 3168

**Comment by williambj1** [comment]
Build, the kext yourself, don't ask how, a simple google search will tell you.
Don't expect too much from this kext at this stage.

**Comment by abdullah-abunada** [comment]
I downloaded itlwm.kext and run the following commands:

` sudo chmod -R 755 itlwm.kext`
`sudo kextload -v itlwm.kext `
and the results was
`itlwm.kext loaded successfully (or already loaded).`

But unfortunately its not working and no wifi driver

**Comment by abdullah-abunada** [comment]
After reading, this step was missed:
**For itlwm u need to create open (without password) hotspot with SSID "Redmi"**
