### ISSUE TITLE
无效ip地址，子网掩码

### ISSUE THREAD

**Issue by Dream-s-Wang** [zxystd/itlwm#137]
当我从其它系统（已连接wifi）重启进入黑苹果时（100%）或休眠启动时（随机发生），会得到一个无效的IP地址（169.254.122.43）和子网掩码（255.255.0.0），我的有效ip地址范围（192.168.1.100-192.168.1.199）和子网掩码（255.255.255.0）。这种情况使用USB有线网卡时，也会发生，请问这是USB网卡的通病吗？

灵越7560
Catalina 10.15.5

**Comment by zxystd** [comment]
ip地址不对说明没有连接上WiFi，你可以在发生这种情况的时候把日志收集起来发给我，在网络设置里把接口删了手动添加回去应该也能恢复网络连接。

log show --last 10m | grep itlwm >~/Desktop/itlwm_log.txt

**Comment by Dream-s-Wang** [comment]
已尝试“在网络设置里把接口删了手动添加回去”，无效，log如下：
[itlwm_log.txt](https://github.com/zxystd/itlwm/files/4778691/itlwm_log.txt)

**Comment by Dream-s-Wang** [comment]
我在使用USB有线网卡时，也遇到过这种情况，只能通过拔插或关机后冷启动解决。我猜想，这会不会时USB网卡的通病？

**Comment by zxystd** [comment]
看到了一堆错误包，猜测是你的路由器的问题，是不是开启了省电模式？

**Comment by Dream-s-Wang** [comment]
谢谢，将路由器信号强度拉满，进入MAC的偏好设置-网络-以太网-高级..,点击DHCP续租，可以获得有效IP了。
