### ISSUE TITLE
似乎与ACPIBatteryManager.kext有冲突

### ISSUE THREAD

**Issue by tomoyowang** [zxystd/itlwm#143]
似乎与ACPIBatteryManager.kext有冲突，不清楚是不是因为ACPIBatteryManager.kext版本太老的缘故。如果挂载了该驱动，ltlwm就会无效，连接不了网络。
[ACPIBatteryManager.kext.zip](https://github.com/zxystd/itlwm/files/4807210/ACPIBatteryManager.kext.zip)

**Comment by zxystd** [comment]
并不是itlwm的问题，这边不予解决。感谢反馈。
