### ISSUE TITLE
AX200蓝牙和wifi同时工作会互相干扰等问题

### ISSUE THREAD

**Issue by AndromedaX7** [zxystd/itlwm#148]
AX200蓝牙和wifi同时工作会互相干扰，
wifi休眠之后就起不来了
连接之后不定时断网
有时找不到接口（网络设置中）
DHCP自动分配不到ip
请问是否支持802.11ac和802.11ax？
是否会支持使用Wi-Fi开启热点？

**Comment by zxystd** [comment]
1.经测试不干扰，如果干扰请连接5gWiFi
2.休眠暂时没遇到问题，可能要等一会才会连上
3.没找到网卡硬件就会驱动不成功，检查efi
4.没有连上WiFi自然获取不到ip
5.以后再说
6.不支持

**Comment by xqgg** [comment]
AX200的蓝牙不能和2.4GWiFi同时使用，试试5G，再不行就没救了
