### ISSUE TITLE
请问 “隔空投送” 会有机会支持吗？

### ISSUE THREAD

**Issue by llkhs** [zxystd/itlwm#152]

**Comment by nieaowei** [comment]
这个问题不可能，哈哈哈，作者估计都不想回答你。

**Comment by zxystd** [comment]
不是可不可能，能做当然能做，是愿不愿意的问题，我认为网速跟稳定性还有设备兼容性才是最重要的，这些东西都需要很长时间来开发维护，其他的，你们有这个能力跟时间可以给我pr，我就一个人，能力有限。

**Comment by zncs520** [comment]
要不成立个基金会，来开发它〈〉

**Comment by llkhs** [comment]
可以可以，别的不多说，能把网卡完美驱动了就行

**Comment by paranoiagu** [comment]
这驱动已经很牛逼了。从一开始只能算连上网，到后来动不动就崩溃重启，到现在基本上已经可以正常用了。
当前最需要解决的是速度慢，偶尔丢包的问题。

**Comment by JunkuiZhang** [comment]
要支持Airdrop是不是要用到IO80211Family啊？
