### ISSUE TITLE
Add License for repo.

### ISSUE THREAD

**Issue by Certseeds** [zxystd/itlwm#16]
开源项目的许可证无论在法律意义上还是在开源层面都还是比较重要的.
是否考虑给repo添加一个LICENSE?
根据'任何人可以查阅并且修改，但是请务必通知我修改的内容，并且保留本作者信息，非常感谢！",似乎是选择可闭源且要在每一个修改过的文件里放置版权声明的Apache协议比较好.

**Comment by zxystd** [comment]
Thanks for your advise.
