### ISSUE TITLE
Intel 8265NGW

### ISSUE THREAD

**Issue by itdawn** [zxystd/itlwm#19]
**The network card can find the signal, but it can't connect. And the SSID cannot be updated in real time.**（This means I changed the SSID but it still shows the original name in the log.）
All connections are shown below:
![itlwm](https://user-images.githubusercontent.com/58105052/77403567-57713300-6deb-11ea-9c3b-1b28d36128d5.png)

**Comment by zxystd** [comment]
maybe latest code has fix this.
