### ISSUE TITLE
能不能把ssid和密码写到info.plist里？让大家自己修改？

### ISSUE THREAD

**Issue by YuHayring** [zxystd/itlwm#20]
could you write ssid and password in info.plist that everyone can edit it

**Comment by williambj1** [comment]
1. 目前不支持密码
2. 有能力自己修改代码编译，测试阶段不提供编译好的文件，你只需要改一个字符串

**Comment by zxystd** [comment]
Now there is some problems with encryptions wifi connection, also we are writing a wifi management client, so we don't need to do this.
