### ISSUE TITLE
为什么不提供Github ketext 下载

### ISSUE THREAD

**Issue by Dukro** [zxystd/itlwm#21]

**Comment by itdawn** [comment]
这个还不成熟，想体验测试自己克隆最新分支，用xcode编译

**Comment by williambj1** [comment]
> 注意：现在虽然能够上网，但是还没有到民用的程度，暂时不提供成品kext，想折腾的可以自行用xcode编译
--远景论坛 作者原话

Kext 本身存在很多问题，完全适合没有开发或者排错能力的人使用，作者不希望被小白打扰

**Comment by zxystd** [comment]
I think the README explain enough, thanks.

**Comment by SuvanCheng** [comment]
> > 注意：现在虽然能够上网，但是还没有到民用的程度，暂时不提供成品kext，想折腾的可以自行用xcode编译
> > --远景论坛 作者原话
> 
> Kext 本身存在很多问题，完全不适合没有开发或者排错能力的人使用，作者不希望被小白打扰

谢谢你让我看到这句话，因为我没账号
