### ISSUE TITLE
Intel 9462 CNVi

### ISSUE THREAD

**Issue by lgariv** [zxystd/itlwm#25]
No internet connection:
![image](https://user-images.githubusercontent.com/5081484/78507386-5b586a00-7788-11ea-8931-ebc5df0f9c44.png)

**Comment by wacxr123** [comment]
蓝牙能用吗

**Comment by lgariv** [comment]
> 蓝牙能用吗

I speak only English...

**Comment by itdawn** [comment]
> 蓝牙能用吗

蓝牙能用，不过没有内建，蓝牙耳机不能用语音

**Comment by hellowworl** [comment]
He said does Intel Bluetooth work?



---Original---

**Comment by williambj1** [comment]
Bluetooth is a separate Kext, IntelBluetoothFirmware.
I'm wondering how you guys found this repo but not the correct one.
