### ISSUE TITLE
How to build the kext?

### ISSUE THREAD

**Issue by epictgames** [zxystd/itlwm#30]
how do i build the kext for mac os 10.15.4 and how do i change the ssid and password?

thank you!

**Comment by epictgames** [comment]
forgot to mention that i have AC8265

**Comment by MohammadtaghiFarkhondekar** [comment]
I tried to making with Xcode but project in Xcode show errors .

**Comment by zxystd** [comment]
Building guide would not be provided here, After it becomes much stable, I will release the binary file for public test(now I can almost touch it), just wait and be patient, thanks.

**Comment by YBN-JUAN** [comment]
支持一个
