### ISSUE TITLE
Network speed is slow

### ISSUE THREAD

**Issue by itdawn** [zxystd/itlwm#31]
I successfully drove the 8265AC with the latest kext, but the network speed was slow.
![image](https://user-images.githubusercontent.com/58105052/78952650-e29b3a00-7b08-11ea-83a5-dacc9d2bdc19.png)

**Comment by epictgames** [comment]
how did you build the kext?

**Comment by zxystd** [comment]
Now the network speed is much better, you can try. Upload speed is still slow.

**Comment by sixian** [comment]
> Now the network speed is much better, you can try. Upload speed is still slow.

9560ac 用最新的build不能连接网络了,上一个版本可以的
[log.txt](https://github.com/zxystd/itlwm/files/4513714/log.txt)

**Comment by williambj1** [comment]
@sixian 

1. 打开系统的偏好设置，删掉网络里所有的端口，右下角应用
1. 终端输入 ```open /Library/Preferences/SystemConfiguration```
1. 删掉
   - **`com.apple.airport.preferences.plist`**
   - **`preferences.plist`**
   - **`NetworkInterfaces.plist`**
   - **`com.apple.network.identification.plist`**
   - **`com.apple.wifi.message-tracer.plist`**
   - 以及目录下所有包含 `enX` 的文件，(可以用 grep 判断)
   - (如果更换过机型，会有个以机型开头的文件，也要删掉)
1. 关机后**彻底断电**，再开机
1. 保险起见，提前备份，这些文件都是自动创建的，本来没有特殊设置的话不会出问题。

**Comment by zxystd** [comment]
> > Now the network speed is much better, you can try. Upload speed is still slow.
> 
> 9560ac 用最新的build不能连接网络了,上一个版本可以的
> [log.txt](https://github.com/zxystd/itlwm/files/4513714/log.txt)

是不是WPA2-PSK的网络？WPA1的一直都有点问题，你可以先用WPA2的网络测试

**Comment by sixian** [comment]
> @sixian
> 
> 1. 打开系统的偏好设置，删掉网络里所有的端口，右下角应用
> 2. 终端输入 `open /Library/Preferences/SystemConfiguration`
> 3. 删掉
>    
>    * **`com.apple.airport.preferences.plist`**
>    * **`preferences.plist`**
>    * **`NetworkInterfaces.plist`**
>    * **`com.apple.network.identification.plist`**
>    * **`com.apple.wifi.message-tracer.plist`**
>    * 以及目录下所有包含 `enX` 的文件，(可以用 grep 判断)
>    * (如果更换过机型，会有个以机型开头的文件，也要删掉)
> 4. 关机后**彻底断电**，再开机
> 5. 保险起见，提前备份，这些文件都是自动创建的，本来没有特殊设置的话不会出问题。

谢谢! 现在可以连接了,可能是之前用过其他的驱动导致的

**Comment by zxystd** [comment]
Now it fix in fbd5b23, thanks.

**Comment by JasonOoi20** [comment]
Thanks. This really works on my case on my AC 9560.

**Comment by mehmetyukcell** [comment]
> Thanks. This really works on my case on my AC 9560. 

How install kext? Or Which kext?

**Comment by JasonOoi20** [comment]
> > Thanks. This really works on my case on my AC 9560. 
> 
> How install kext? Or Which kext?

Just sideload the itlwm.kext using console or put it inside the clover kext/other/ folder.

**Comment by Cxp1220** [comment]
大佬，我现在用的itlwm.kext，网速比较慢，插上网线速度也不正常了，我想暂时停用itlwm，然后就把它关了，但是关了之后有线也连不上网了，怎么解决

**Comment by Cxp1220** [comment]
为啥不回复我

**Comment by williambj1** [comment]
Off topic
