### ISSUE TITLE
My Results

### ISSUE THREAD

**Issue by epictgames** [zxystd/itlwm#32]
i have built the kext, also me wifi very slow but no problems running, no reboot, no kernal panic
using Intel AC8265 Hp Kaby Lake
bluetooth firmware + itlwm loaded, 3 mbps download , 0 upload

i have made 4 kexts to load, each one for different router.

its useful but i still prefer usb wifi since i have support for airplay with it.

loading kext from terminal using kextload. 

Thank you!

**Comment by deniro98** [comment]
Have same speed 9mg download, 0 upload

**Comment by zxystd** [comment]
upload speed has been fix. download speed will also soon.

**Comment by zxystd** [comment]
Upload issue fix in fbd5b23, thanks.
