### ISSUE TITLE
加载kext后没反应，log很短

### ISSUE THREAD

**Issue by dlhxr** [zxystd/itlwm#33]
自己编译了一下，加载后没啥反应，log也很短。。。
[log.log](https://github.com/zxystd/itlwm/files/4472260/log.log)

**Comment by zxystd** [comment]
重启再加载一次试试

**Comment by dlhxr** [comment]
结果也是一样，又是到iwm_load_firmware就没有了。。。
[log2.log](https://github.com/zxystd/itlwm/files/4472845/log2.log)

**Comment by zxystd** [comment]
product id是多少？

**Comment by dlhxr** [comment]
A370，我看源码里面有这个id啊。。。

**Comment by dlhxr** [comment]
IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/CNVW@14,3
PciRoot(0x0)/Pci(0x14,0x3)
倒是我同时用HoRNDIS.kext，连着手机上网，也是生成了一个ethernet，冲突？

**Comment by zxystd** [comment]
这个id是支持的，我朋友的也是这个id，他可以用，不过也是有时候跟你一样会卡在这，重启几次可以。嗯，你也可以试试把HORNDIS创建的网络接口删了再试试。

**Comment by dlhxr** [comment]
试过删掉HORNDIS的接口，而且前面测试的时候都没插usb手机。我再多试试看吧，有进展再更新，谢谢啦！

**Comment by yxh139270** [comment]
我的也是9560，开始也是加载了没反应，多试几次就好了。现在就是网速非常慢。能正常驱动。

**Comment by dlhxr** [comment]
和https://github.com/zxystd/itlwm/issues/39一样，BIOS里面开关一次就能驱动…
