### ISSUE TITLE
panic(cpu 0 caller 0xffffff801604c32a): Kernel trap at 0xffffff7f9a38942f, type 14=page fault, registers:

### ISSUE THREAD

**Issue by lifsux** [zxystd/itlwm#34]
panic(cpu 0 caller 0xffffff801604c32a): Kernel trap at 0xffffff7f9a38942f, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000000000, CR3: 0x000000002cf8f000, CR4: 0x00000000003626e0
RAX: 0x0000000000000000, RBX: 0x0000000000000000, RCX: 0x0000000000000000, RDX: 0x0000000000000001
RSP: 0xffffff9135fa3bc0, RBP: 0xffffff9135fa3bd0, RSI: 0x0000000000000000, RDI: 0xffffff80fbe9da80
R8:  0x0000000000000001, R9:  0x0000000000000001, R10: 0x0000000979e72996, R11: 0xffffff801680a1c0
R12: 0x0000000000000000, R13: 0x0000000000000000, R14: 0xffffff803c21c4c0, R15: 0xffffff80fbe3e000
RFL: 0x0000000000010246, RIP: 0xffffff7f9a38942f, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000000000000, Error code: 0x0000000000000000, Fault CPU: 0x0, PL: 0, VF: 1

Backtrace (CPU 0), Frame : Return Address
0xffffff9135fa3620 : 0xffffff8015f215cd 
0xffffff9135fa3670 : 0xffffff801605a3c5 
0xffffff9135fa36b0 : 0xffffff801604bf7e 
0xffffff9135fa3700 : 0xffffff8015ec7a40 
0xffffff9135fa3720 : 0xffffff8015f20c97 
0xffffff9135fa3820 : 0xffffff8015f21087 
0xffffff9135fa3870 : 0xffffff80166c2c7c 
0xffffff9135fa38e0 : 0xffffff801604c32a 
0xffffff9135fa3a60 : 0xffffff801604c028 
0xffffff9135fa3ab0 : 0xffffff8015ec7a40 
0xffffff9135fa3ad0 : 0xffffff7f9a38942f 
0xffffff9135fa3bd0 : 0xffffff7f9a3899bd 
0xffffff9135fa3c00 : 0xffffff7f9a389718 
0xffffff9135fa3c70 : 0xffffff7f9a39c03d 
0xffffff9135fa3d30 : 0xffffff7f9a3a7c13 
0xffffff9135fa3de0 : 0xffffff8016608c06 
0xffffff9135fa3e40 : 0xffffff8016608741 
0xffffff9135fa3ef0 : 0xffffff8016607ade 
0xffffff9135fa3f50 : 0xffffff801660a296 
0xffffff9135fa3fa0 : 0xffffff8015ec713e 
      Kernel Extensions in backtrace:
         com.zhong.AppleIntelWiFi(1.0)[E9AFB6BC-7D2B-3E9B-B799-658E962DCD55]@0xffffff7f9a360000->0xffffff7f9a3f2fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[1B1F3BBB-9212-3CF9-94F8-8FEF0D3ACEC4]@0xffffff7f96cb3000
            dependency: com.apple.iokit.IO80211Family(1200.12.2b1)[043696D2-853D-3775-A87F-79C42F324EEB]@0xffffff7f9a205000
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[3F6EDFDE-6EF7-38D8-8006-C4EE6DB4D4B5]@0xffffff7f9696e000

BSD process name corresponding to current thread: kernel_task
Boot args: -v darkwake=0 gfxrst=1

Mac OS version:
19E287

Kernel version:
Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Kernel UUID: AB0AA7EE-3D03-3C21-91AD-5719D79D7AF6
Kernel slide:     0x0000000015c00000
Kernel text base: 0xffffff8015e00000
__HIB  text base: 0xffffff8015d00000
System model name: MacBookPro14,1 (Mac-B4831CEBD52A0C4C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 40699984304

**Comment by zxystd** [comment]
Please contact to the real author, thanks.
