### ISSUE TITLE
网卡 intel 9560(9462)  deviceid=02f0没发正常驱动

### ISSUE THREAD

**Issue by pengkool** [zxystd/itlwm#35]
9560网卡 device=02f0 无法正常驱动
在代码中加入02f0后，启动日志见附件：
[test2.log](https://github.com/zxystd/itlwm/files/4481091/test2.log)

**Comment by pengkool** [comment]
02f0能支持吗？

**Comment by zxystd** [comment]
According to the linux code, 0x02f0 is a gen2 device, which is same pic id as ax201, so, just wait the `itlwmx` work done.

**Comment by zxystd** [comment]
duplicate with #88
