### ISSUE TITLE
【已解决，原理未知】ac9560 网卡进win10系统之后再进macOS无法顺利驱动

### ISSUE THREAD

**Issue by Mr-UFO** [zxystd/itlwm#39]
ac9560 网卡进win10系统之后再进macOS无法顺利驱动：
After logging in win10, wireless card can not be  driven in macOS anyway.
现已经找到解决办法：进BIOS把无线网卡关掉，重启再进BIOS打开无线网卡，之后才能驱动。

小白，不知道原理是什么？不知道其他人有没有也遇到类似的BUG？

AC9560 联想Y7000 10.15.4

**Comment by zxystd** [comment]
??????

**Comment by dlhxr** [comment]
和你一样，我是Y540的Intel 9560。。。谜一样
https://github.com/zxystd/itlwm/issues/33

**Comment by zxystd** [comment]
win10下跟macos下驱动固件版本不一致导致的，无法解决，只能断电，或者两个用同一个版本的驱动固件

**Comment by dlhxr** [comment]
弱弱的问，openbsd下的iwm-9000-34对应windows的哪一版固件呢？这有什么规律可以找到对应版本么？我看最新的win版是21.80.2.1
