### ISSUE TITLE
Unable to build in mojave

### ISSUE THREAD

**Issue by guaychou** [zxystd/itlwm#41]
Hey please help me to build in mojave version

i cannot compile it 

![image](https://user-images.githubusercontent.com/29087469/79839392-aad0a400-83de-11ea-86b7-55389f4ba70f.png)

![image](https://user-images.githubusercontent.com/29087469/79839481-c340be80-83de-11ea-8f2a-ff8144ce9781.png)

**Comment by zxystd** [comment]
Change the three target `BaseSDK` to `MacOS` will help you. And here is not suggest to discuss how to build or use it. Thanks.

**Comment by guaychou** [comment]
@zxystd i already change it to MacOS and still cannot compiled

![image](https://user-images.githubusercontent.com/29087469/79846090-33077700-83e8-11ea-8251-363a1c3dc3b8.png)

**Comment by mojo2012** [comment]
The problem seems to be that the linux/types.h cannot be found in on of the files. Also Even if you fix this by replacing it with a relative import, it still can't build as fails with this error:
`Assigning to 'bus_addr_t' (aka 'unsigned long long') from incompatible type 'nullptr_t'`
