### ISSUE TITLE
Hp Probook 450 G6 intelwifi 9560ac Catalina 10.15.4

### ISSUE THREAD

**Issue by mehmetyukcell** [zxystd/itlwm#44]
![Ekran Resmi 2020-04-24 20 31 21](https://user-images.githubusercontent.com/62822060/80240517-9f91a880-866a-11ea-8cc1-cb3eb35640d7.png)
PciRoot(0x0)/Pci(0x14,0x3)
IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/CNVW@14,3

Hp Probook 450 G6 intelwifi 9560ac LOG.TXT
[log.txt](https://github.com/zxystd/itlwm/files/4528872/log.txt)

**Comment by zxystd** [comment]
Thanks for your test.
