### ISSUE TITLE
小米pro ac8265 10.15.4 目前还是链接上一会就没网了

### ISSUE THREAD

**Issue by renyichan** [zxystd/itlwm#45]
[test.log.zip](https://github.com/zxystd/itlwm/files/4529738/test.log.zip)
连接依然还在，系统也分配了ip，在上网几分钟之后无网速无法访问internet。这是我拉出来的日志，希望对你有用

**Comment by zxystd** [comment]
上传还有问题,不做大流量的上传操作就不会断(比如跑速、上传),还在修复中,目前下载速度是正常了,跑速30mbps左右

**Comment by renyichan** [comment]
好的，辛苦了这么晚还在看问题。加油

**Comment by Cheers0606** [comment]
哈哈 我是想着跑个测速的试试看，然后跑完就没网了，应该是同个问题，上传太多流量了。

**Comment by zxystd** [comment]
上传已经修好了，最新的提交 fbd5b23，感谢你的测试。
