### ISSUE TITLE
how to  use?

### ISSUE THREAD

**Issue by RomanceLink** [zxystd/itlwm#47]
I dont konw  how to use this ,please help me,i download the file，but i dont konw how to make to ac9462 drive!

**Comment by PeLLmEn** [comment]
1) You have to download and install xcode in your Mac OS.
2) Run in terminal `git clone https://github.com/zxystd/itlwm.git`
3) Locate to `itlwm` folder and open `itlwm.xcodeproj` with xcode.
4) You have to compile 3 kext `itlwm.kext` , `itlwmx.kext` and `itl80211.kext`. Because i'm not using xcode, I don't know how to get it build all properly, I've just selected settings, that recommended by project, targeted `fw_gen.sh` and sometimes it gives normal results. But i don't understand how does it work, so if somebody can explain i'll be grateful.

**Comment by zxystd** [comment]
I will publish the release after I have fix the upload speed issue.

**Comment by flexwin** [comment]
when will be publishing the release?

**Comment by basedtho** [comment]
i can't load the kexts

```
71 Debug sudo kextload -v itlwm.kext itl80211.kext itlwmx.kext
Requesting load of /Users/tho/Library/Developer/Xcode/DerivedData/itlwm-bwyrhxridbgsnugsfhmjokladmaz/Build/Products/Debug/itlwm.kext.
/Users/tho/Library/Developer/Xcode/DerivedData/itlwm-bwyrhxridbgsnugsfhmjokladmaz/Build/Products/Debug/itlwm.kext failed to load - (libkern/kext) dependency load failed; check the system/kernel logs for errors or try kextutil(8).
Requesting load of /Users/tho/Library/Developer/Xcode/DerivedData/itlwm-bwyrhxridbgsnugsfhmjokladmaz/Build/Products/Debug/itl80211.kext.
/Users/tho/Library/Developer/Xcode/DerivedData/itlwm-bwyrhxridbgsnugsfhmjokladmaz/Build/Products/Debug/itl80211.kext failed to load - (libkern/kext) dependency load failed; check the system/kernel logs for errors or try kextutil(8).
Requesting load of /Users/tho/Library/Developer/Xcode/DerivedData/itlwm-bwyrhxridbgsnugsfhmjokladmaz/Build/Products/Debug/itlwmx.kext.
/Users/tho/Library/Developer/Xcode/DerivedData/itlwm-bwyrhxridbgsnugsfhmjokladmaz/Build/Products/Debug/itlwmx.kext loaded successfully (or already loaded)

```

(built successfully, only had to substitute an ocurrence of nullptr with a 0 in one place)

**Comment by PeLLmEn** [comment]
@basedtho don't install it to your system!!!!!! Just use it in opencore (oc/kext) or in clover.

**Comment by basedtho** [comment]
it won't connect either way

**Comment by mehmetyukcell** [comment]
when will be publishing the release?

**Comment by mehmetyukcell** [comment]
> 5\. const char

Where load the kexts.

**Comment by mehmetyukcell** [comment]
> * You have to download and install xcode in your Mac OS.
> * Run in terminal `git clone https://github.com/zxystd/itlwm.git`
> * Locate to `itlwm` folder and open `itlwm.xcodeproj` with xcode.
> * In `/itlwm/mac80211.cpp` search for:
>   `    static const char *ssid_name = "ssdt"; static const char *ssid_pwd = "zxyssdt112233";`
>   and change `ssdt` and `zxyssdt112233` to your wifi `SSID` and `password`
> * In `/itlwmx/itlwmx.cpp` search for:
>   `const char *ssid_name = "ssdt"; const char *ssid_pwd = "zxyssdt112233";`
>   and change `ssdt` and `zxyssdt112233` to your wifi `SSID` and `password`
> * After changing you have to compile 3 kext `itlwm.kext` , `itlwmx.kext` and `itl80211.kext`. Because i'm not using xcode, I don't know how to get it build all properly, I've just selected settings, that recommended by project, targeted `fw_gen.sh` and sometimes it gives normal results. But i don't understand how does it work, so if somebody can explain i'll be grateful.
> * I have AC 3168 adapter. I've installed all 3 kext, rebooted and finaly connection worked for me but with very poor speed ~1Mbit/s.

Where load the kexts? Clover EFI or Library extensions

**Comment by PeLLmEn** [comment]
Clover or opencore efi

**Comment by mehmetyukcell** [comment]
> Clover or opencore efi

Thanks... But, xcode build only one kext. İo80211

**Comment by Whandcz** [comment]
> 三叶草或opencore efi
你好  ，最新版我编译时 遇到Build input file cannot be found: '/Users/*/Desktop/itlwm-master/itlwm/FwBinary.cpp'   我折腾了好久也没解决    请问 你能指点我一下怎么解决吗

**Comment by Roshaanv** [comment]
> 1. You have to download and install xcode in your Mac OS.
> 2. Run in terminal `git clone https://github.com/zxystd/itlwm.git`
> 3. Locate to `itlwm` folder and open `itlwm.xcodeproj` with xcode.
> 4. In `/itlwm/mac80211.cpp` search for:
>    `    static const char *ssid_name = "ssdt"; static const char *ssid_pwd = "zxyssdt112233";`
>    and change `ssdt` and `zxyssdt112233` to your wifi `SSID` and `password`
> 5. In `/itlwmx/itlwmx.cpp` search for:
>    `const char *ssid_name = "ssdt"; const char *ssid_pwd = "zxyssdt112233";`
>    and change `ssdt` and `zxyssdt112233` to your wifi `SSID` and `password`
> 6. After changing you have to compile 3 kext `itlwm.kext` , `itlwmx.kext` and `itl80211.kext`. Because i'm not using xcode, I don't know how to get it build all properly, I've just selected settings, that recommended by project, targeted `fw_gen.sh` and sometimes it gives normal results. But i don't understand how does it work, so if somebody can explain i'll be grateful.
> 7. I have AC 3168 adapter. I've installed all 3 kext, rebooted and finaly connection worked for me but with very poor speed ~1Mbit/s.

Thank you for your instruction! I followed it, but I only get 2 out of 3 kexts compiled with xcode (itwlmx.kext doesn't get created for me). Any ideas what went wrong?

**Comment by mehmetyukcell** [comment]
> > 1. You have to download and install xcode in your Mac OS.
> 
> > 2. Run in terminal `git clone https://github.com/zxystd/itlwm.git`
> 
> > 3. Locate to `itlwm` folder and open `itlwm.xcodeproj` with xcode.
> 
> > 4. In `/itlwm/mac80211.cpp` search for:
> 
> >    `    static const char *ssid_name = "ssdt"; static const char *ssid_pwd = "zxyssdt112233";`
> 
> >    and change `ssdt` and `zxyssdt112233` to your wifi `SSID` and `password`
> 
> > 5. In `/itlwmx/itlwmx.cpp` search for:
> 
> >    `const char *ssid_name = "ssdt"; const char *ssid_pwd = "zxyssdt112233";`
> 
> >    and change `ssdt` and `zxyssdt112233` to your wifi `SSID` and `password`
> 
> > 6. After changing you have to compile 3 kext `itlwm.kext` , `itlwmx.kext` and `itl80211.kext`. Because i'm not using xcode, I don't know how to get it build all properly, I've just selected settings, that recommended by project, targeted `fw_gen.sh` and sometimes it gives normal results. But i don't understand how does it work, so if somebody can explain i'll be grateful.
> 
> > 7. I have AC 3168 adapter. I've installed all 3 kext, rebooted and finaly connection worked for me but with very poor speed ~1Mbit/s.
> 
> 
> 
> Thank you for your instruction! I followed it, but I only get 2 out of 3 kexts compiled with xcode (itwlmx.kext doesn't get created for me). Any ideas what went wrong?

With two kexts— can be tried

**Comment by zxystd** [comment]
just select `itlwm` target and compile, and itl80211 and itlwmx are not necessary to use, you don't need to compile or use them.

**Comment by Roshaanv** [comment]
> just select `itlwm` target and compile, and itl80211 and itlwmx are not necessary to use, you don't need to compile or use them.

I've now compiled itlwm.kext and put it into 'Clover/kexts/others'. After restarting, it still doesn't work.
Then I tried it with kextload and get "(libkern/kext) failed to load" or sometimes "(libkern/kext) dependency load failed". 

I'm on a Matebook X Pro (2018) with Intel AC 8275 and disabled SIP

**Comment by Longcoming** [comment]
Install the kext using hackintool to L/E.

**Comment by Roshaanv** [comment]
> Install the kext using hackintool to L/E.

Tried that too, didn't work :/

**Comment by Drun555** [comment]
>     1. You have to download and install xcode in your Mac OS.
> 
>     2. Run in terminal `git clone https://github.com/zxystd/itlwm.git`
> 
>     3. Locate to `itlwm` folder and open `itlwm.xcodeproj` with xcode.
> 
>     4. In `/itlwm/mac80211.cpp` search for:
>        `    static const char *ssid_name = "ssdt"; static const char *ssid_pwd = "zxyssdt112233";`
>        and change `ssdt` and `zxyssdt112233` to your wifi `SSID` and `password`
> 
>     5. In `/itlwmx/itlwmx.cpp` search for:
>        `const char *ssid_name = "ssdt"; const char *ssid_pwd = "zxyssdt112233";`
>        and change `ssdt` and `zxyssdt112233` to your wifi `SSID` and `password`
> 
>     6. After changing you have to compile 3 kext `itlwm.kext` , `itlwmx.kext` and `itl80211.kext`. Because i'm not using xcode, I don't know how to get it build all properly, I've just selected settings, that recommended by project, targeted `fw_gen.sh` and sometimes it gives normal results. But i don't understand how does it work, so if somebody can explain i'll be grateful.
> 
>     7. I have AC 3168 adapter. I've installed all 3 kext, rebooted and finaly connection worked for me but with very poor speed ~1Mbit/s.

Hey! 

Can you tell how you targeted fw_gen.sh, please? I can't compile the kext because I don't have **FwBinary.cpp**, which should be created by **fw_gen.sh**, which is a Build Tool for **fwgen**, but building it don't make any files. I'm completely lost now.

**Comment by hackslashX** [comment]
> > ```
> > 1. You have to download and install xcode in your Mac OS.
> > 
> > 2. Run in terminal `git clone https://github.com/zxystd/itlwm.git`
> > 
> > 3. Locate to `itlwm` folder and open `itlwm.xcodeproj` with xcode.
> > 
> > 4. In `/itlwm/mac80211.cpp` search for:
> >    `    static const char *ssid_name = "ssdt"; static const char *ssid_pwd = "zxyssdt112233";`
> >    and change `ssdt` and `zxyssdt112233` to your wifi `SSID` and `password`
> > 
> > 5. In `/itlwmx/itlwmx.cpp` search for:
> >    `const char *ssid_name = "ssdt"; const char *ssid_pwd = "zxyssdt112233";`
> >    and change `ssdt` and `zxyssdt112233` to your wifi `SSID` and `password`
> > 
> > 6. After changing you have to compile 3 kext `itlwm.kext` , `itlwmx.kext` and `itl80211.kext`. Because i'm not using xcode, I don't know how to get it build all properly, I've just selected settings, that recommended by project, targeted `fw_gen.sh` and sometimes it gives normal results. But i don't understand how does it work, so if somebody can explain i'll be grateful.
> > 
> > 7. I have AC 3168 adapter. I've installed all 3 kext, rebooted and finaly connection worked for me but with very poor speed ~1Mbit/s.
> > ```
> 
> 
> Hey!
> 
> 
> Can you tell how you targeted fw_gen.sh, please? I can't compile the kext because I don't have **FwBinary.cpp**, which should be created by **fw_gen.sh**, which is a Build Tool for **fwgen**, but building it don't make any files. I'm completely lost now.

There's a `fw_gen.sh` script in the source. Simply execute it to create the necessary file.
