### ISSUE TITLE
大佬，请问编译生的itlwm.kext如何使用？

### ISSUE THREAD

**Issue by kai2ou** [zxystd/itlwm#50]
macos 10.13.6，使用Xcode 9.4.1编译生成的itlwm.kext，然后将其copy到EFI里面重启？

**Comment by YuHayring** [comment]
http://bbs.pcbeta.com/viewthread-1848739-1-1.html

**Comment by kai2ou** [comment]
> http://bbs.pcbeta.com/viewthread-1848739-1-1.html

出现以下错误：Can't record kext in identifier lookup dictionary; no identifier.

**Comment by zxystd** [comment]
https://github.com/zxystd/itlwm/issues/30#issuecomment-612550528
