### ISSUE TITLE
Intel 8275: Works but random Kernel Panic

### ISSUE THREAD

**Issue by mircoianese** [zxystd/itlwm#51]
Hello!
First of all thanks for this amazing work. I've tested your kext on my 2018 Matebook X Pro with Intel 8275AC Wireless card. 

It works but I get random Kernel Panic (especially if I do network intensive stuff, like a speedtest).

Aside from that everything seems working great: ping from terminal has good response and I do not see any Packet loss from that (when there is no other network activity).

If you need logs or anything else please let me know. 
Thanks

**Comment by zxystd** [comment]
is the master latest code version?

**Comment by mircoianese** [comment]
> is the master latest code version?

Actually I'm not totally sure. Could you provide me a compiled kext download link for the last version?
Thanks!

**Comment by zxystd** [comment]
[itlwm.kext.zip](https://github.com/zxystd/itlwm/files/4535569/itlwm.kext.zip)

Try this one built by latest code, since there is still have upload issue I am trying to fix. But the download speed is fine and would not caused kernel panic I think.

WIFI ssid and password are hardcoded `ssdt` `zxyssdt112233`

**Comment by mircoianese** [comment]
I've created a guest network and tried this kext. 

For now it seems to be stable (usually it crashes in less than 3 minutes). I will of course keep testing.
I can confirm the issue with upload speeds.

If you need any other testing done on this card let me know!
Thanks

**Comment by zxystd** [comment]
Thanks, If kernel panic happened again, please send me the panic log, it will help me to locate the problem.

**Comment by mircoianese** [comment]
I can confirm: no more kernel panics with this kext. I've also setup the environment to compile from source myself - last version I just compiled still has upload speed issues, but everything else seems fine!

Thank you for your work
