### ISSUE TITLE
Hello Intel Wifi Card

### ISSUE THREAD

**Issue by tolgasonkaya** [zxystd/itlwm#53]
Hello I have Intel AC-3165 card. I want to help you with your project to test kexts.
But I do not know how to compile with Xcode as I update the kext here, I want to provide you with information.

**Comment by mehmetyukcell** [comment]
> Hello I have Intel AC-3165 card. I want to help you with your project to test kexts.
> 
> But I do not know how to compile with Xcode as I update the kext here, I want to provide you with information.

https://intelwifi.0xcc.pw burda kext var ama Wi-Finizin idsi uyumlu mu bilmiyorum?

**Comment by tolgasonkaya** [comment]
Hocam ben osxinfodan TolgaSonn linkteki kext farklı bi projeye ait bu arkadaş ayrı bir kext deniyor çin forumunda konusu var fakat üyelik davetiye sistemiyle ücretli yürüyor

**Comment by mehmetyukcell** [comment]
> Hocam ben osxinfodan TolgaSonn linkteki kext farklı bi projeye ait bu arkadaş ayrı bir kext deniyor çin forumunda konusu var fakat üyelik davetiye sistemiyle ücretli yürüyor  

Onu anlayamadım kardeşim ben de burdan kodlarla kext oluşturmaya izin yok mu yani?

**Comment by zxystd** [comment]
^qUxJg$c1cdd294dfdd92eb542ad63b164cedc82e2047cdc
thanks, here you can see the binary file i have just compile

**Comment by tolgasonkaya** [comment]
Var hocam xcode ile kext oluşturabiliyorsanız sorun yok ben o kadar bilgili değilim

**Comment by tolgasonkaya** [comment]
> #51
> thanks, here you can see the binary file i have just compile

Thanks I try kext and send message

**Comment by tolgasonkaya** [comment]
Hello there. I load the Kexti L / E directory with Hackintool, but the system does not recognize my wifi card.

**Comment by Longcoming** [comment]
Sometimes,there is connection,sometimes there is not.

**Comment by zxystd** [comment]
> Hello there. I load the Kexti L / E directory with Hackintool, but the system does not recognize my wifi card.

what is your card? and the product id where you can see in hackintool pci category

**Comment by tolgasonkaya** [comment]
> > Hello there. I load the Kexti L / E directory with Hackintool, but the system does not recognize my wifi card.
> 
> what is your card? and the product id where you can see in hackintool pci category

Now installed. id=3165. 
kext sometimes connects sometimes not.

**Comment by mehmetyukcell** [comment]
> > > Hello there. I load the Kexti L / E directory with Hackintool, but the system does not recognize my wifi card.
> 
> > 
> 
> > what is your card? and the product id where you can see in hackintool pci category
> 
> 
> 
> Now installed. id=3165. 
> 
> kext sometimes connects sometimes not.
> 
> 

Hacklntool ile wifi bilgilerini paylaş fotoğraf şeklinde.

**Comment by tolgasonkaya** [comment]
> > > > Hello there. I load the Kexti L / E directory with Hackintool, but the system does not recognize my wifi card.
> > 
> > 
> > > 
> > 
> > 
> > > what is your card? and the product id where you can see in hackintool pci category
> > 
> > 
> > Now installed. id=3165.
> > kext sometimes connects sometimes not.
> 
> Hacklntool ile wifi bilgilerini paylaş fotoğraf şeklinde.

[url=https://hizliresim.com/WoHMSq][img]https://i.hizliresim.com/WoHMSq.png[/img][/url]

**Comment by tolgasonkaya** [comment]
> > > > Hello there. I load the Kexti L / E directory with Hackintool, but the system does not recognize my wifi card.
> > 
> > 
> > > 
> > 
> > 
> > > what is your card? and the product id where you can see in hackintool pci category
> > 
> > 
> > Now installed. id=3165.
> > kext sometimes connects sometimes not.
> 
> Hacklntool ile wifi bilgilerini paylaş fotoğraf şeklinde.

[url=https://hizliresim.com/WoHMSq][img]https://i.hizliresim.com/WoHMSq.png[/img][/url]
