### ISSUE TITLE
Connect to unsecured network

### ISSUE THREAD

**Issue by coretm21** [zxystd/itlwm#54]
Hi, 
Is there a way to connect to a network that is not having WPA2 as security ? Because when I put nothing as Password (in info.plist) to connect to a network that doesn't have any security, and the right string as BSSID, it's just not connecting after loading the kext. Is that normal ?

Btw big big thanks and GG to you for your amazing work, it's working well on my 7265AC !!

**Comment by MarshalX** [comment]
Hmmm, info.plist?

**Comment by zxystd** [comment]
Maybe you are not using my kext named by itlwm ?
