### ISSUE TITLE
Intel 9462 CNVi

### ISSUE THREAD

**Issue by lgariv** [zxystd/itlwm#57]
With the latest version - I get 40 mbps download which is the same as using my TL-WN821N USB adapter. incredible!

**However**, download speed is around 0.1 mbps, which is actually slower than what I got in previous release (right after adding support to this card). When upload speed is fixed - it's pretty much ready for everyday use in my opinion, as long as you don't care for switching networks easily that much (using wifi at work only / working from home, etc).

Amazing improvement!

**Comment by zxystd** [comment]
Now the issue fix in fbd5b23, thanks.
