### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by demonlj** [zxystd/itlwm#65]
osx: 10.15.3
xcode: 11.4.1
code: latest commit:883354164327c76825ab5fe89e8ea9eb28473f36
```
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "YXX7XALBVX" with a private key was found. (in target 'itl80211' from project 'itlwm')

** BUILD FAILED **
```

**Comment by mehmetyukcell** [comment]
> osx: 10.15.3
> 
> xcode: 11.4.1
> 
> code: latest commit:883354164327c76825ab5fe89e8ea9eb28473f36
> 
> ```
> 
> note: Using new build system
> 
> note: Building targets in parallel
> 
> note: Planning build
> 
> note: Constructing build description
> 
> error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "YXX7XALBVX" with a private key was found. (in target 'itl80211' from project 'itlwm')
> 
> 
> 
> ** BUILD FAILED **
> 
> ```

Please Xcode prefrences Apple İd sign in

**Comment by demonlj** [comment]
already sign in with apple id and apple development certificates, still got errors
```
error: No account for team "YXX7XALBVX". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials. (in target 'itl80211' from project 'itlwm')
error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "YXX7XALBVX" with a private key was found. (in target 'itl80211' from project 'itlwm')
```

**Comment by zxystd** [comment]
Just remove the signature of the three target and compile again.
![image](https://user-images.githubusercontent.com/16227538/80957191-4a595200-8e35-11ea-89af-7cb992cd9129.png)

**Comment by demonlj** [comment]
it works. Thanks
