### ISSUE TITLE
Really interested about your work 

### ISSUE THREAD

**Issue by PaulMagos** [zxystd/itlwm#66]
1. Is there any chance to make a visual selection tool for wifi ? 
2. An idea if we use your previous version of your project (AppleIntelWifi) to scan wifi and then use this ethernet spoofed version for accessing it ? 

Not very familiar with this kind of things, sorry if I make noobs questions.

- Paul

**Comment by zxystd** [comment]
Of course yes, but I don't want to use IO80211Family until the network connection is stable.

**Comment by PaulMagos** [comment]
Really impressed btw, thanks for answering!
