### ISSUE TITLE
 Creating Kext with Xcode

### ISSUE THREAD

**Issue by tolgasonkaya** [zxystd/itlwm#68]
I don't know how to compile kext with Xcode. Can you help me. Or would you send a video.

**Comment by mehmetyukcell** [comment]
Tolga kardeşim merhaba, xcode prefrences kısmında öncelikle apple id ile giriş yap.

**Comment by mehmetyukcell** [comment]
https://github.com/zxystd/itlwm/issues/47#issuecomment-619223159 burdakileri de yapman gerekiyor kendi ağ ismini ve şifreni dediği girmelisin...

**Comment by tolgasonkaya** [comment]
Hocam önce deneme amaçlı kexti düzenlemeden oluşturayım da gerisini hallederim projeyi tekrar çektim xcode ile açtım apple hesabımda açık xcode de şimdi ne yapmalıyım
