### ISSUE TITLE
请问有内测群吗？

### ISSUE THREAD

**Issue by yaozaiyu** [zxystd/itlwm#7]
ax200希望加入内测！晚上有几个小时时间！

**Comment by williambj1** [comment]
目前大佬手上有 AX200 了，如果你有 IOKit 或者 C++ 开发经验可以考虑拉你进开发群

**Comment by yaozaiyu** [comment]
@williambj1 我是web开发的，问一下进度如何了，ax200

**Comment by zxystd** [comment]
注意提交信息可以知道进度，另外可以看远景帖子也会不定期更新进度

**Comment by zxystd** [comment]
如果加入了ax200支持，欢迎来测试，这个ISSUE先关闭了，感谢。
