### ISSUE TITLE
有计划支持wpa2-enterprise 吗？

### ISSUE THREAD

**Issue by charlesld** [zxystd/itlwm#71]
wpa2下认证正常使用，wpa2企业级无法使用。  

![image](https://user-images.githubusercontent.com/23304239/81362603-cb556980-9113-11ea-9e7b-cf6051d92ee1.png)

特来咨询下作者，是否有支持计划？

![image](https://user-images.githubusercontent.com/23304239/81362738-21c2a800-9114-11ea-90c6-06d6064f2afb.png)

**Comment by charlesld** [comment]
另，加入的网络wpa2会被误认为wep
![image](https://user-images.githubusercontent.com/23304239/81363007-cb099e00-9114-11ea-8070-f6645a40842a.png)

**Comment by zxystd** [comment]
额，你应该是用的别人的kext。

**Comment by WarrenChan1027** [comment]
所以现在可以支持了，公司的wifi我连不了。。

**Comment by WarrenChan1027** [comment]
所以现在可以支持了吗？公司的WiFi我还是连不了。

**Comment by charlesld** [comment]
@WarrenChan1027  我是买了个网卡，能用公司的网络，intel的只能用家里的。

**Comment by WarrenChan1027** [comment]
是买的USB无线网卡吗

**Comment by charlesld** [comment]
@WarrenChan1027  是的。 https://www.jianshu.com/p/964217d72ef1

**Comment by WarrenChan1027** [comment]
不好意思，你发的这个简书的链接我打不开。。你能发个具体的型号吗

**Comment by charlesld** [comment]
@WarrenChan1027  CF-812AC
