### ISSUE TITLE
睡眠后网络失效且无法关闭连接

### ISSUE THREAD

**Issue by blickers** [zxystd/itlwm#74]
编译出 itl80211.kext 和 itlwm.kext 放入 EFI 的 Clover kext目录里，启动直接联网成功。
一般上上网没有发现明显问题，但是系统一旦进入睡眠并唤醒后，网络就会失效，并且在系统偏好设置里面再也无法关闭并重新启用网络。

**Comment by blickers** [comment]
多次测试发现，这个问题有一定的随机性。有时唤醒后会失效，有时不会。有点奇怪。

**Comment by mehmetyukcell** [comment]
> 多次测试发现，这个问题有一定的随机性。有时唤醒后会失效，有时不会。有点奇怪。

Please English for me

**Comment by tg567** [comment]
> > 多次测试发现，这个问题有一定的随机性。有时唤醒后会失效，有时不会。有点奇怪。
> 
> Please English for me

He said after compile the code, success connect to internet. In dayily useage, there is no big problem, but when system go sleep and wake up, computer disconnect from internet, and you can't restart internet in system setting. 
My english suck, hope you can understand.
