### ISSUE TITLE
Can't load the kext - AC9462

### ISSUE THREAD

**Issue by JulioCMLP** [zxystd/itlwm#75]
![received_862190774291936](https://user-images.githubusercontent.com/22485628/82009005-c7ee4080-9633-11ea-959b-29e074371ae8.jpeg)
I compiled the kext from the latest source code... But when I try to load it I get that error, I also put it in my clover EFI but it doesn't work, can someone help me?

**Comment by zxystd** [comment]
Firstly you should change the file owner permission and then load it.

sudo chown -R root:wheel itlwm.kext
sudo kextload itlwm.kext

also, put it in boatloader driver folder can work.
