### ISSUE TITLE
Trouble with fw_gen.sh

### ISSUE THREAD

**Issue by awsmct** [zxystd/itlwm#78]
When i try run fw_gen.sh i get this error:
./fw_gen.sh: line 11: [[!-f: command not found

Last master branch, what i do wrong?

**Comment by arch-dev** [comment]
Hi. Edit line 11 as follows:
[[ ! -f
Spaces are important else it will not work.

**Comment by ksh1t1z** [comment]
Hi, I'm getting this error after putting in spaces.

line 11: syntax error in conditional expression: unexpected token `;'
line 11: syntax error near `;'
line 11: `if [[ ! -f $target_file]]; then'

**Comment by awsmct** [comment]
ur line should looks like "if [[ ! -f $target_file ]]; then"

**Comment by awsmct** [comment]
> Hi. Edit line 11 as follows:
> [[ ! -f
> Spaces are important else it will not work.

I need help again.
After start fw_gen.sh i get next errors:

./fw_gen.sh: line 13: /itlwm/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 14: /itlwm/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 20: /itlwm/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 21: /itlwm/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 22: /itlwm/firmware/*: No such file or directory
./fw_gen.sh: line 23: /itlwm/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 24: /itlwm/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 25: /itlwm/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 28: /itlwm/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 30: /itlwm/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 36: /itlwm/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 39: /itlwm/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 40: /itlwm/FwBinary.cpp: No such file or directory

**Comment by arch-dev** [comment]
Add this line just before "target_file=...":
PROJECT_DIR="."

**Comment by awsmct** [comment]
> PROJECT_DIR="."

Thanks you, man.
If you are dev, fix this on branch, please.

**Comment by arch-dev** [comment]
I'm not dev of this project, sorry. @zxystd is dev and I think he will fix this shortly

**Comment by ksh1t1z** [comment]
can you create a pull request fixing all these

**Comment by ksh1t1z** [comment]
What did I do wrong?

line 9: ${"PROJECT_DIR"}/itlwm/FwBinary.cpp: bad substitution
line 14: $target_file: ambiguous redirect
line 15: $target_file: ambiguous redirect
line 21: $target_file: ambiguous redirectline 22: $target_file: ambiguous redirect
line 23: ./itlwm/firmware/*: No such file or directory
line 24: $target_file: ambiguous redirect
line 25: $target_file: ambiguous redirect
line 26: $target_file: ambiguous redirect
line 31: $target_file: ambiguous redirect
line 37: $target_file: ambiguous redirect
line 40: $target_file: ambiguous redirect
line 41: $target_file: ambiguous redirect

**Comment by arch-dev** [comment]
Send your fw_gen.sh so I can check it please

**Comment by ksh1t1z** [comment]
Sorry for the trouble.
#!/bin/sh

#  fw_gen.sh
#  itlwm
#
#  Created by qcwap on 2020/3/10.
#  Copyright © 2020 钟先耀. All rights reserved.
PROJECT_DIR="."
target_file="${"PROJECT_DIR"}/itlwm/FwBinary.cpp"
fw_files=${PROJECT_DIR}/itlwm/firmware/*

if [[ ! -f $target_file ]]; then

echo "//  itlwm\n\n//  Copyright © 2020 钟先耀. All rights reserved." >$target_file
echo "#include \"FwData.h\"">>$target_file

for fw in $fw_files; do
    fw_file_name=`basename $fw`
    fw_var_name=${fw_file_name//./_}
    fw_var_name=${fw_var_name//-/_}
    echo "">>$target_file
    echo "const unsigned char ${fw_var_name}[] = {">>$target_file
    xxd -i <$fw >>$target_file
    echo "};">>$target_file
    echo "">>$target_file
    echo "const long int ${fw_var_name}_size = sizeof(${fw_var_name});">>$target_file
done

echo "">>$target_file

echo "const struct FwDesc fwList[] = {">>$target_file
i=0;
for fw in $fw_files; do
    fw_file_name=`basename $fw`
    fw_var_name=${fw_file_name//./_}
    fw_var_name=${fw_var_name//-/_}
    echo "{IWL_FW(\"$fw_file_name\", $fw_var_name, ${fw_var_name}_size)},">>$target_file
    let i+=1
done
echo "};">>$target_file
echo "const int fwNumber = $i;">>$target_file

fi

**Comment by arch-dev** [comment]
Change this line
target_file="${"PROJECT_DIR"}/itlwm/FwBinary.cpp"
to this
target_file="${PROJECT_DIR}/itlwm/FwBinary.cpp"

**Comment by zxystd** [comment]
I think I have fix this problem, try using the latest commit? thanks for your attention.

**Comment by awsmct** [comment]
> I think I have fix this problem, try using the latest commit? thanks for your attention.

Say please, where i can find .kext after build? I can't find it

**Comment by ksh1t1z** [comment]
~/Library/Developer/Xcode/DerivedData

**Comment by zxystd** [comment]
If ur using the latest commit, you can get it on the projectpath/Build/Products/Debug/itlwm.kext

**Comment by awsmct** [comment]
nothing in projectpath and in Xcode/DerivedData

**Comment by kai2ou** [comment]
I just tried it, and it is fine.

**Comment by ksh1t1z** [comment]
I'm still getting this
![Screen Shot 2020-05-16 at 4 06 16 PM](https://user-images.githubusercontent.com/49852633/82117370-35fb4a80-978f-11ea-8020-8b3f4348eb74.png)

**Comment by zxystd** [comment]
just build again

**Comment by awsmct** [comment]
> If ur using the latest commit, you can get it on the projectpath/Build/Products/Debug/itlwm.kext

I downloaded last commit, build fwBinarry, build itlwm and still get morning in project folder (itlwm-master)

**Comment by awsmct** [comment]
> I'm still getting this
> 
> ![Screen Shot 2020-05-16 at 4 06 16 PM](https://user-images.githubusercontent.com/49852633/82117370-35fb4a80-978f-11ea-8020-8b3f4348eb74.png)
> 
> 


https://github.com/zxystd/itlwm/issues/78#issuecomment-629614810

**Comment by awsmct** [comment]
> just build again

Add please this line to fw_gen.sh


https://github.com/zxystd/itlwm/issues/78#issuecomment-629614810

**Comment by kai2ou** [comment]
> get morning



> > If ur using the latest commit, you can get it on the projectpath/Build/Products/Debug/itlwm.kext
> 
> I downloaded last commit, build fwBinarry, build itlwm and still get morning in project folder (itlwm-master)

just build itlwm

**Comment by ksh1t1z** [comment]
Go to Library/Developer/Xcode/DerivedData/itlwm.../Build/Products/Debug

**Comment by ksh1t1z** [comment]
Thank to everyone here. I succeeded finally after hours.

**Comment by ksh1t1z** [comment]
> > If ur using the latest commit, you can get it on the projectpath/Build/Products/Debug/itlwm.kext
> 
> I downloaded last commit, build fwBinarry, build itlwm and still get morning in project folder (itlwm-master)

https://github.com/zxystd/itlwm/issues/78#issuecomment-629625098

**Comment by arch-dev** [comment]
@awsmct since problem has been solved close this issue please so we can clean issue list
