### ISSUE TITLE
Kernel panic on Intel Dual Band AC3165

### ISSUE THREAD

**Issue by arch-dev** [zxystd/itlwm#79]
Hi. I'm following this amazing project since my laptop has the AC3165 chipset installed and I've have been looking for a solution to make Intel WiFi working on my hackintosh for years.
I've built this project using latest version of xcode but when I load the kext I get kernel panic. Is it due to wrong 7265/7265D ucode firmware version?

[Kernel_2020-05-14-205324_MacBook-Pro.txt](https://github.com/zxystd/itlwm/files/4638171/Kernel_2020-05-14-205324_MacBook-Pro.txt)

**Comment by zxystd** [comment]
Seems `memcpy` function broken? I have 3165 test card and haven't encounter this problem, maybe you can try to load again?

**Comment by arch-dev** [comment]
Ok I found the problem I think, it seems that changing ssid_name and ssid_pwd with mine is the cause. Should I create a new WiFi network with default credentials?

**Comment by zxystd** [comment]
What is your WiFi encrypt info?

**Comment by arch-dev** [comment]
WPA/WPA2-Personal

**Comment by arch-dev** [comment]
I've tried disabling WPA2 in source code allowing only WPA and now it connects successfully, but after 10 seconds kernel panic is triggered. So seems that disabling WPA2 in code has changed something but is not sufficient yet.

**Comment by zxystd** [comment]
I will switch to my 3165 card and test later.

**Comment by arch-dev** [comment]
Ok wait for you thanks

**Comment by zxystd** [comment]
Tested with 3165, no kernel panic happened...
Maybe you can try the latest code and find whether other kexts caused the kp. Thanks.

**Comment by arch-dev** [comment]
Ok will try and keep you updated. Thank you for your work.

**Comment by Stevemoretz** [comment]
I have 3165 no kernel panic happened for me

**Comment by leopck** [comment]
I have a 3165 as well, no kernel panic for me. Worked perfectly for me for 1 week, rebooted multiple times as well. No issue.

**Comment by arch-dev** [comment]
Ok works perfectly with latest commits. Thanks.
