### ISSUE TITLE
Stupid Question

### ISSUE THREAD

**Issue by 0x47726567** [zxystd/itlwm#8]
What is the difference between this project ( itlwm ) and  AppleIntelWifiAdapter?

**Comment by williambj1** [comment]
I think this is already explained in README

**Comment by deniro98** [comment]
> What is the difference between this project ( itlwm ) and AppleIntelWifiAdapter?

This is S/L/E Kext, work with open wifi.

**Comment by williambj1** [comment]
> > What is the difference between this project ( itlwm ) and AppleIntelWifiAdapter?
> 
> itlwm is S/L/E Kext, work with open wifi.

You'd better stop joking.

**Comment by 0x47726567** [comment]
Welp, i guess i'm blind.

**Comment by williambj1** [comment]
> Because the integrated 80211 ported from OpenBSD in that project has so many things require testing, I came up with an idea of porting the entire iwm driver from OpenBSD, and this repo is the result.

I thought I'm blind as well.
