### ISSUE TITLE
Intel Wireless ac 3165- Link broken and no upload speed showing as ethernet

### ISSUE THREAD

**Issue by rahulmangla19** [zxystd/itlwm#83]
![Screenshot 2020-05-18 at 7 42 42 AM](https://user-images.githubusercontent.com/64670907/82168625-c85d3480-98dc-11ea-940c-07434a45cc97.png)
![Screenshot 2020-05-18 at 7 44 10 AM](https://user-images.githubusercontent.com/64670907/82168634-ce531580-98dc-11ea-871d-94c31485ed9a.png)

just to make to note to Developer and waiting For Fix.
Using Kext complied itlwm and itl80211. it working in clover and in opencore it panic spontaneously and not useful at all. 
kindly Fix the issue for broken speed ,protocol as ethernet and also support for opencore.
![Screenshot 2020-05-18 at 7 42 42 AM](https://user-images.githubusercontent.com/64670907/82168625-c85d3480-98dc-11ea-940c-07434a45cc97.png)

**Comment by rahulmangla19** [comment]
[Uploading Rahul.zip…]()
kext used
[itl80211.kext.zip](https://github.com/zxystd/itlwm/files/4641713/itl80211.kext.zip)

**Comment by rahulmangla19** [comment]
[itlwm.kext.zip](https://github.com/zxystd/itlwm/files/4641722/itlwm.kext.zip)
[itl80211.kext.zip](https://github.com/zxystd/itlwm/files/4641726/itl80211.kext.zip)

**Comment by zxystd** [comment]
fix in 7eb758e
