### ISSUE TITLE
Trouble w 5GHz Wi-Fi

### ISSUE THREAD

**Issue by awsmct** [zxystd/itlwm#84]
Are this driver support 5GHz Wi-Fi and can SSID contain spaces? or strongly needed w/o it?

**Comment by testkam2018** [comment]
i've tried with 5Ghz - no luck

**Comment by awsmct** [comment]
> i've tried with 5Ghz - no luck

Whats a name of your network?

**Comment by balenv** [comment]
i´ve changed the name of my 5g network to the one hardcoded ans it works,not at 5g speeds but it works

**Comment by awsmct** [comment]
> i´ve changed the name of my 5g network to the one hardcoded ans it works,not at 5g speeds but it works

what does u mean by "one hardcoded"? Name consist of one word?

**Comment by balenv** [comment]
the kext that im using has an ssdt and password hardcoded, where it only connect to that hardcoded network name and password. i´ve downloaded it from and issue open on this github

**Comment by ferhatmeric** [comment]
No problem, both 5GHz and 2.4GHz wifi channels can be used. Max speed I get is 30Mbps.

**Comment by balenv** [comment]
can you share the kext you are using?

**Comment by mehmetyukcell** [comment]
> No problem, both 5GHz and 2.4GHz wifi channels can be used. Max speed I get is 30Mbps.

Ferhat Bey Merhabalar, intel 9560 wifi kart var bende bu kexti denesem önerir misiniz?

**Comment by ferhatmeric** [comment]
> can you share the kext you are using?

This video has detailed description about kext file and how to load.

https://www.youtube.com/watch?v=ICpgYtzbxP8

**Comment by ferhatmeric** [comment]
> > No problem, both 5GHz and 2.4GHz wifi channels can be used. Max speed I get is 30Mbps.
> 
> Ferhat Bey Merhabalar, intel 9560 wifi kart var bende bu kexti denesem önerir misiniz?

Merhaba,
9560 serisi ile ilgili karışık sonuçlar var demiş, bence deneyebilirsiniz.

Intel(R) Dual Band Wireless-AC 9560 | 8086:0030, 8086:0034 8086:0038, 8086:003c 8086:0230, 8086:0234 8086:0238, 8086:023c 8086:2030, 8086:2034 8086:4030, 8086:4034 8086:4234 | Mixed results (some are CNVi, some are PCIe) | Yes
-- | -- | -- | --
