### ISSUE TITLE
Which kext should i install?

### ISSUE THREAD

**Issue by balenv** [zxystd/itlwm#86]
Hi!, i want to thank the dev for the hours put on to this project. I also have a question.

So, i´ve been using the itlwm.kext with clover, (this one https://github.com/zxystd/itlwm/issues/51#issuecomment-61956699 )on macOS catalina and now on mojave it works fine. 

I´ve seen some post were people are getting 30mb/s and the kext that im using only gets to 10mb/s and almost no upload speeds.

 I know theres also other kexts like AppleIntelWifi, but im confused of which one should i install.

**Comment by zxystd** [comment]
The upload speed issue is need to be fix, so to some extent this kext is not stable(network speed) now as well as I haven't publish in release.
