### ISSUE TITLE
bulid错误

### ISSUE THREAD

**Issue by aiyunyuner** [zxystd/itlwm#87]
![6EA57448-CF49-4BA1-8901-7513CAB827F5](https://user-images.githubusercontent.com/63837650/82749013-e47b3d00-9dd8-11ea-8934-8ca8129259a6.jpeg)
我该怎么解决？

**Comment by arch-dev** [comment]
Type in terminal
sudo chmod +x /path/to/fw_gen.sh

**Comment by aiyunyuner** [comment]
谢谢，已解决。
