### ISSUE TITLE
Kernel panic after loading kext and using modem

### ISSUE THREAD

**Issue by MarshalX** [zxystd/itlwm#9]
Modem: **Huawei e3372h-153**

Maybe this is not important at all, but I noticed such a feature.

Steps:
1. load kext 
2. *auto*connect to wifi, using eithernet
3. disable wifi hotspot
4. plug in modem in usb
....
kernel panic

As I remember same issue occurred with https://joshuawise.com/horndis (eithernet from phone by usb)

**Comment by vasishath** [comment]
Omg I use horndis kext and I faced the same kernel panic

**Comment by zxystd** [comment]
So many things I haven't handled, but this stage these things are not very important rather than smooth stable connect to the internet and hardware compatibility, I will record it. Thanks.

**Comment by zxystd** [comment]
Maybe fix it isn't necessary because this situation is rare...
