### ISSUE TITLE
Request a wifi ui selector todo

### ISSUE THREAD

**Issue by Stevemoretz** [zxystd/itlwm#91]
Hi thanks for all the great hard work,you've said it before that you rather do the ui,after the crashes and speed problems are gone, with your latest commit you have solved the above issues, so now we'd love to see the ui selector replaced with the hard-coded ssid and password.That would be very nice and takes this kext one more big step to the release stage.

**Comment by williambj1** [comment]
WIP :p

**Comment by Klingens13** [comment]
> WIP :p
Not to be rude, but can we get an very rough ETA based on priority?

**Comment by Stevemoretz** [comment]
@zxystd sorry to ask, but you closed it because it has been implemented,or because it will be implemented?

**Comment by zxystd** [comment]
It is WIP, you can see it in my another repo call HeliPort. Any related issus can turn to there. thanks.

https://github.com/zxystd/HeliPort
