### ISSUE TITLE
Matebook X Pro2020，ac9560无法使用

### ISSUE THREAD

**Issue by kdzmwl** [zxystd/itlwm#95]
![IMG_20200530_211746](https://user-images.githubusercontent.com/37917970/83329256-071ac380-a2bb-11ea-8593-5c78cb1c2b4a.jpg)
<img width="697" alt="截屏2020-05-30 下午9 19 13" src="https://user-images.githubusercontent.com/37917970/83329352-99bb6280-a2bb-11ea-8941-ebb732b4efd5.png">

执行加载命令后如图所示，也没有出现WiFi、以太网等设置。

**Comment by lsvih** [comment]
没记错的话这个是 gen2 的卡，等作者的 itlwmx 吧。。#88 #93

**Comment by zxystd** [comment]
productId? 用hacintool在pci那一栏可以看到

**Comment by tsingui** [comment]
Nuc8i7beh AC9560 doesn't work

**Comment by weidongbcn** [comment]
你放在什么位置？我直接放到clover的kext-other里头，重启就可以用了。是2个文件。

**Comment by kdzmwl** [comment]
> 你放在什么位置？我直接放到clover的kext-other里头，重启就可以用了。是2个文件。

我直接放在桌面上，用terminal加载的。引导是oc

**Comment by weidongbcn** [comment]
![QQ20200602-143940](https://user-images.githubusercontent.com/23153588/83521323-56d9d480-a4df-11ea-9128-461a6a501254.png)
![QQ20200602-144019](https://user-images.githubusercontent.com/23153588/83521342-622d0000-a4df-11ea-8000-ee8cf7babb57.png)
我用oc启动，console中调用，也可以用。

**Comment by kdzmwl** [comment]
> ![QQ20200602-143940](https://user-images.githubusercontent.com/23153588/83521323-56d9d480-a4df-11ea-9128-461a6a501254.png)
> ![QQ20200602-144019](https://user-images.githubusercontent.com/23153588/83521342-622d0000-a4df-11ea-8000-ee8cf7babb57.png)
> 我用oc启动，console中调用，也可以用。

需要将驱动放在特定位置吗？我直接放在了桌面。
另：请问您的笔记本型号和我的是同一款吗？

**Comment by weidongbcn** [comment]
![QQ20200603-080000](https://user-images.githubusercontent.com/23153588/83601207-6e14d280-a570-11ea-951a-0e017e5661e7.png)
![QQ20200603-080039](https://user-images.githubusercontent.com/23153588/83601276-8ab10a80-a570-11ea-8ff4-71c6f5ef6be8.png)

你的设备属性表有弄好吗？

**Comment by kdzmwl** [comment]
> ![QQ20200603-080000](https://user-images.githubusercontent.com/23153588/83601207-6e14d280-a570-11ea-951a-0e017e5661e7.png)
> ![QQ20200603-080039](https://user-images.githubusercontent.com/23153588/83601276-8ab10a80-a570-11ea-8ff4-71c6f5ef6be8.png)
> 
> 你的设备属性表有弄好吗？

新人，对config中项目的含义不是特别理解。我只需要用命令加载，也需要在config中添加这些项目吗？如果方便，是否可以添加一下QQ详谈

**Comment by zxystd** [comment]
如果你不打算回答我上面提的问题的话，那这个issue可以关了。

**Comment by kdzmwl** [comment]
> 如果你不打算回答我上面提的问题的话，那这个issue可以关了。

<img width="1304" alt="截屏2020-06-03 下午2 39 41" src="https://user-images.githubusercontent.com/37917970/83604659-1fcff580-a5a9-11ea-9069-5217b3ecbc18.png">
非常抱歉！没有及时回复您的问题。网卡应该是ac9560，但是在hackintools里面显示是上图的样子。

**Comment by zxystd** [comment]
ProductId 是0x02F0，这个id跟ax201一致，属于二代设备，将会在另一个驱动itlwmx里支持。
