### ISSUE TITLE
intel 9560ac appears as Ethernet 2 on Network preferences and it has connect internet, interestingly

### ISSUE THREAD

**Issue by mehmetyukcell** [zxystd/itlwm#97]
![Ekran Resmi 2020-05-31 00 35 17](https://user-images.githubusercontent.com/62822060/83339451-a305f880-a2d6-11ea-9463-df3a9781300b.png)
Built new itlwmx kext, loaded  with
cd desktop 
sudo chown -R root:wheel itlwm.kext
sudo kextload itlwm.kext

successfully and my 9560ac appears as Ethernet 2 on Network preferences. Also, on Hackintool it shows in the attached photo. However, it has connected intetnet with USB WİFİ Asus nano ac53. demount USB WİFİ but still connect internet. Surprise.... interesting..Also, builted kext 488,4 mb.

![Ekran Resmi 2020-05-31 00 27 44](https://user-images.githubusercontent.com/62822060/83339404-1e1adf00-a2d6-11ea-82ac-e7cf6e30b043.png)
![Ekran Resmi 2020-05-31 00 31 17](https://user-images.githubusercontent.com/62822060/83339406-207d3900-a2d6-11ea-935e-4957e4a791e3.png)

**Comment by zxystd** [comment]
4884mb... how did you do that?

**Comment by mehmetyukcell** [comment]
> 4884mb... how did you do that?

with Xcode build kext and product iltwm.kext :)I did not understand too. Also, pci ac9560 and cnvi ac9560 is there a difference between the two?

**Comment by fanvantan** [comment]
I have nearly same issue with 9560AC (device ID 9DF) in Mojave. 
After loading kext, network shows Ethernet 2 (not WI-FI so there is no SSID to connect). And Ethernet 2 doesn't receive DHCP, apparently.
Hackintool shows Cannon Point-LP CNVi [Wireless-AC] like @mehmetyukcell
