### ISSUE TITLE
Invalid signature -67030 

### ISSUE THREAD

**Issue by shomerchang** [zxystd/itlwm#99]
驱动加载到最后 总是提示
Successfully loaded /Users/zhang/Desktop/itlwm.kext.
/Users/zhang/Desktop/itlwm.kext successfully loaded (or already loaded).
Invalid signature -67030 for kext <OSKext 0x7fed8862a080 [0x7fff87a1bb60]> { URL = "file:///Users/zhang/Desktop/itlwm.kext/", ID = "com.zxystd.itlwm" }
不知道为什么没成功，
kextstat|grep itl                      
  167    0 0xffffff7f8469c000 0xf80000   0xf80000   com.zxystd.itlwm (1) 32D299EF-B1DE-384C-A105-67654C96AAEC <18 13 6 5 3 1>
也unload不了
我是ac9560，系统：10.15.5

**Comment by Basstorm** [comment]
Successfully loaded /Users/zhang/Desktop/itlwm.kext.
这不是成功了么
下面的可以忽略

**Comment by shomerchang** [comment]
> Successfully loaded /Users/zhang/Desktop/itlwm.kext.
> 这不是成功了么
> 下面的可以忽略

但是网络里 什么变化也没有

**Comment by zxystd** [comment]
log show --last boot | grep itlwm >itlwm.txt

看看日志

**Comment by armen181** [comment]
I receive almost the same message. OS 10.15.4, nothing happens  
[itlwm.txt](https://github.com/zxystd/itlwm/files/4707573/itlwm.txt)

**Comment by shomerchang** [comment]
[itlwm.txt](https://github.com/zxystd/itlwm/files/4707643/itlwm.txt)
这是我的日志 @zxystd

**Comment by zxystd** [comment]
productid是不是02f0?如果是的话这是二代设备，等itlwmx可以用吧

**Comment by shomerchang** [comment]
> productid是不是02f0?如果是的话这是二代设备，等itlwmx可以用吧

![截屏2020-05-31 下午9 57 48](https://user-images.githubusercontent.com/17776090/83354305-6267b700-a38a-11ea-9228-863ca7d4e7f2.png)
看不懂这图

**Comment by zxystd** [comment]
a370是可以驱动的，彻底断电关机几分钟，再启动试试

**Comment by williambj1** [comment]
https://github.com/zxystd/itlwm/issues/31#issuecomment-617542780

**Comment by shomerchang** [comment]
> [#31 (comment)](https://github.com/zxystd/itlwm/issues/31#issuecomment-617542780)

niubility,成功了

**Comment by shomerchang** [comment]
> a370是可以驱动的，彻底断电关机几分钟，再启动试试

清了一下 那些配置文件，成功了，感谢大佬，大佬加油！
